source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '>= 2.7.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.3.0'
gem 'sdoc', '~> 0.4.1',          group: :doc
gem 'spring',        group: :development
gem 'haml', '~> 4.0.6'
gem 'bootstrap-sass', '~> 3.3.5.1'
gem 'devise', '~> 3.5.1'
gem 'simple_form', '~> 3.1.0'